const LS='dietControlEvidence_v4';
const OLD_LS='weightHealthPWA_v1';
const today=()=>new Date().toISOString().slice(0,10);
const defaultState={profile:{birthDate:'',sex:'male',height:192,targetWeight:92,calorieTarget:1850,proteinTarget:150},metrics:[],meals:[],activities:[],health:[]};
let state=JSON.parse(localStorage.getItem(LS)||localStorage.getItem(OLD_LS)||'null')||defaultState;
state.profile={...defaultState.profile,...(state.profile||{})};
state.metrics=state.metrics||[];state.meals=state.meals||[];state.activities=state.activities||[];state.health=state.health||[];
const SOURCES={
  nice:{name:'NICE NG246 — Overweight and obesity management (2025)',url:'https://www.nice.org.uk/guidance/ng246'},
  who:{name:'WHO — Obesity and overweight / physical activity',url:'https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight'},
  aha:{name:'AHA 2026 CKM guideline',url:'https://professional.heart.org/en/science-news/2026-guideline-for-the-prevention-detection-evaluation-and-management-of-ckm-syndrome/top-things-to-know'},
  ada:{name:'ADA Standards of Care in Diabetes — 2026',url:'https://diabetesjournals.org/care/issue/49/Supplement_1'},
  kdigo:{name:'KDIGO 2024 CKD Guideline',url:'https://kdigo.org/guidelines/ckd-evaluation-and-management/'},
  acsm:{name:'ACSM Physical Activity Guidelines',url:'https://acsm.org/education-resources/trending-topics-resources/physical-activity-guidelines/'},
  cdc:{name:'CDC — Steps for Losing Weight',url:'https://www.cdc.gov/healthy-weight-growth/losing-weight/index.html'}
};
const INFO={
 bmi:{title:'BMI — מדד מסת הגוף',formula:'משקל בק״ג ÷ (גובה במטרים)²',meaning:'מדד סקר שימושי לעודף משקל, אך אינו מודד ישירות שומן בטני או הרכב גוף. לכן האפליקציה אינה משתמשת בו לבדו.',improve:'אם הוא גבוה יחד עם היקף מותניים מוגבר: ירידה הדרגתית במשקל, תזונה שניתן להתמיד בה, פעילות אירובית ואימוני כוח.',source:'nice',strength:'מבוסס היטב — מדד סקר, לא אבחנה יחידה'},
 whtr:{title:'יחס מותניים/גובה',formula:'היקף מותניים בס״מ ÷ גובה בס״מ',meaning:'מודד את השומן המרכזי ביחס למבנה הגוף. כלל פשוט ושימושי הוא לשאוף להיקף מותניים הנמוך ממחצית הגובה.',improve:'הפחתת שומן בטני באמצעות ירידה מתונה במשקל, פעילות סדירה ושילוב אימוני כוח.',source:'nice',strength:'מבוסס היטב להערכת השמנה מרכזית'},
 waist:{title:'היקף מותניים',formula:'מדידה אופקית של היקף הבטן לפי פרוטוקול עקבי',meaning:'שומן בטני קשור לסיכון קרדיו־מטבולי גם כאשר BMI אינו גבוה מאוד.',improve:'עקוב אחר המגמה, לא מדידה בודדת. ירידה של כמה ס״מ לאורך זמן היא לרוב סימן חיובי גם כשהמשקל נע לאט.',source:'aha',strength:'מבוסס היטב'},
 whr:{title:'יחס מותניים/ירכיים',formula:'היקף מותניים ÷ היקף ירכיים',meaning:'מדד לפיזור שומן. הוא משלים BMI והיקף מותניים אך פחות שימושי למעקב יומיומי.',improve:'אותן פעולות שמפחיתות שומן בטני: מאזן אנרגטי מתאים, אירובי וכוח.',source:'who',strength:'מדד משלים'},
 bp:{title:'לחץ דם',formula:'נמדד בסיסטולי/דיאסטולי; האפליקציה אינה מחשבת את המדידה עצמה',meaning:'לחץ דם הוא גורם סיכון מרכזי ללב, מוח וכליות. פרשנות נכונה מבוססת על מדידות חוזרות ותמונה קלינית.',improve:'מדידה ביתית נכונה, ירידה במשקל אם נדרש, פעילות, תזונה בסגנון DASH/ים־תיכוני, הפחתת נתרן וטיפול תרופתי לפי רופא.',source:'aha',strength:'מבוסס היטב'},
 a1c:{title:'HbA1c',formula:'בדיקת מעבדה המשקפת בקירוב גלוקוז ממוצע לאורך מספר חודשים',meaning:'משמשת לסקר/אבחון ולמעקב אחר סוכרת, אך יש מצבים שבהם התוצאה עלולה להיות מושפעת מגורמים אחרים.',improve:'משקל בריא יותר, תזונה איכותית, פעילות סדירה וטיפול מותאם אישית אם יש טרום־סוכרת או סוכרת.',source:'ada',strength:'מבוסס היטב'},
 glucose:{title:'גלוקוז בצום',formula:'בדיקת מעבדה לאחר צום לפי הנחיות המעבדה',meaning:'משקף את ויסות הסוכר בנקודת זמן. תוצאה חריגה אינה מפוענחת באפליקציה כאבחנה סופית.',improve:'פעילות גופנית, ירידה במשקל במידת הצורך, איכות פחמימות וסיבים, ושינה מספקת.',source:'ada',strength:'מבוסס היטב'},
 ldl:{title:'LDL-C',formula:'מדווח במעבדה או מחושב לפי שיטת המעבדה',meaning:'יעד LDL אינו מספר אחיד לכולם; הוא תלוי בסיכון הקרדיווסקולרי הכולל ובהיסטוריה הרפואית.',improve:'תזונה דלה בשומן רווי ועשירה בסיבים מסיסים, פעילות, משקל תקין וטיפול תרופתי כאשר הוא מותווה.',source:'aha',strength:'מבוסס היטב'},
 nonhdl:{title:'Non-HDL-C',formula:'כולסטרול כללי − HDL-C',meaning:'מייצג את כלל הכולסטרול בחלקיקים האטרוגניים. שימושי במיוחד לצד LDL וטריגליצרידים.',improve:'אותן פעולות המשפרות פרופיל שומנים: תזונה, פעילות, ירידה במשקל וטיפול תרופתי לפי סיכון.',source:'aha',strength:'מבוסס היטב'},
 tg:{title:'טריגליצרידים',formula:'בדיקת מעבדה',meaning:'יכולים לעלות עקב עודף אנרגיה, אלכוהול, סוכרים פשוטים, תנגודת לאינסולין וגורמים נוספים.',improve:'הפחתת עודף קלורי, סוכרים פשוטים ואלכוהול; פעילות סדירה וירידה במשקל אם נדרשת.',source:'aha',strength:'מבוסס היטב'},
 tghdl:{title:'יחס TG/HDL',formula:'טריגליצרידים ÷ HDL-C',meaning:'יחס תצפיתי שעשוי לשקף סיכון מטבולי בחלק מהאוכלוסיות, אך אין לו סף אבחנתי אוניברסלי.',improve:'התמקד בשיפור הטריגליצרידים, HDL והכושר — לא במספר היחס בפני עצמו.',source:'aha',strength:'מדד משלים — לא יעד טיפולי עצמאי'},
 egfr:{title:'eGFR',formula:'מחושב במעבדה מקריאטינין ונתונים נוספים לפי משוואה מקובלת',meaning:'אומדן לתפקוד הסינון הכלייתי. פירוש נכון תלוי גם ב-UACR, במשך הזמן ובהקשר הקליני.',improve:'איזון לחץ דם וסוכר, הימנעות מנזק כלייתי וטיפול רפואי מותאם. אין “להעלות eGFR” באמצעות טריק תזונתי.',source:'kdigo',strength:'מבוסס היטב'},
 uacr:{title:'UACR',formula:'יחס אלבומין/קריאטינין בשתן',meaning:'מודד אלבומין בשתן ומשמש יחד עם eGFR להערכת סיכון כלייתי.',improve:'שליטה בלחץ דם וסוכר וטיפול רפואי לפי הסיבה והסיכון. תוצאה חריגה דורשת לעיתים אישור במדידה חוזרת.',source:'kdigo',strength:'מבוסס היטב'},
 activity:{title:'פעילות שבועית',formula:'סך דקות פעילות אירובית + ימי אימוני כוח',meaning:'היעד הכללי למבוגרים הוא 150–300 דקות פעילות מתונה בשבוע, או 75–150 דקות נמרצת, ובנוסף כוח לפחות יומיים.',improve:'הגדל בהדרגה זמן פעילות ושמור על שילוב אירובי + כוח.',source:'acsm',strength:'מבוסס היטב'},
 weighttrend:{title:'קצב ירידה במשקל',formula:'שינוי משקל לאורך זמן; עדיפות למגמה של מספר שבועות',meaning:'ירידה הדרגתית נוטה להיות בת־קיימא יותר מירידה מהירה. תנודות יומיות משקפות לעיתים מים ולא שומן.',improve:'כוון לגירעון מתון, עקביות ותזונה שניתן להחזיק לאורך זמן; אל תרדוף אחרי תנודה יומית.',source:'cdc',strength:'מבוסס היטב'}
};
function save(){localStorage.setItem(LS,JSON.stringify(state));renderAll()}
function age(){if(!state.profile.birthDate)return null;const b=new Date(state.profile.birthDate),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n<new Date(n.getFullYear(),b.getMonth(),b.getDate()))a--;return a}
function latestMetric(){return [...state.metrics].sort((a,b)=>a.date.localeCompare(b.date)).at(-1)||{}}
function latestHealth(){return [...state.health].sort((a,b)=>a.date.localeCompare(b.date)).at(-1)||{}}
function calc(m=latestMetric()){
 const h=+state.profile.height||0,w=+m.weight||0,wa=+m.waist||0,hip=+m.hip||0;
 const bmi=h&&w?w/((h/100)**2):null, whtr=h&&wa?wa/h:null,whr=wa&&hip?wa/hip:null;
 return {bmi,whtr,whr};
}
function calcHealth(h=latestHealth()){
 const tc=+h.totalChol||0,hdl=+h.hdl||0,tg=+h.triglycerides||0,sbp=+h.sbp||0,dbp=+h.dbp||0;
 return {nonHdl:tc&&hdl?tc-hdl:null,tgHdl:tg&&hdl?tg/hdl:null,pulsePressure:sbp&&dbp?sbp-dbp:null,map:sbp&&dbp?dbp+(sbp-dbp)/3:null};
}
function bmiStatus(v){if(v==null)return['—','']; if(v<18.5)return['נמוך','warn'];if(v<25)return['טווח תקין','good'];if(v<30)return['עודף משקל','warn'];return['השמנה','bad']}
function whtrStatus(v){if(v==null)return['—',''];if(v<.4)return['נמוך','warn'];if(v<.5)return['יעד מועדף','good'];if(v<.6)return['סיכון מוגבר','warn'];return['סיכון גבוה','bad']}
function whrStatus(v){if(v==null)return['—',''];const lim=state.profile.sex==='male'?.90:.85;return v<lim?['מתחת לסף','good']:['מעל הסף','warn']}
function waistStatus(v){if(!v)return['—',''];const s=state.profile.sex==='male';const warn=s?94:80,high=s?102:88;if(v<warn)return['מתחת לסף פעולה','good'];if(v<high)return['מוגבר','warn'];return['גבוה','bad']}
function bpStatus(s,d){s=+s;d=+d;if(!s||!d)return['—',''];if(s<120&&d<80)return['תקין','good'];if(s<130&&d<80)return['מוגבר','warn'];if(s<140&&d<90)return['יתר לחץ דם דרגה 1','warn'];if(s>=180||d>=120)return['ערך חמור — נדרשת הערכה רפואית','bad'];return['יתר לחץ דם דרגה 2','bad']}
function a1cStatus(v){v=+v;if(!v)return['—',''];if(v<5.7)return['בטווח תקין','good'];if(v<6.5)return['טווח טרום־סוכרת','warn'];return['בטווח אבחנתי לסוכרת*','bad']}
function glucoseStatus(v){v=+v;if(!v)return['—',''];if(v<100)return['בטווח תקין','good'];if(v<126)return['טווח טרום־סוכרת','warn'];return['בטווח אבחנתי לסוכרת*','bad']}
function tgStatus(v){v=+v;if(!v)return['—',''];if(v<150)return['תקין','good'];if(v<200)return['גבולי','warn'];if(v<500)return['גבוה','bad'];return['גבוה מאוד','bad']}
function ldlStatus(v){v=+v;if(!v)return['—',''];if(v<100)return['נמוך יחסית','good'];if(v<130)return['קרוב לטווח המקובל','warn'];if(v<160)return['מוגבר','warn'];return['גבוה','bad']}
function score(){const m=latestMetric(),c=calc(m);let pts=0,n=0; if(c.bmi){n++;pts+=c.bmi>=18.5&&c.bmi<25?100:c.bmi<30?65:35} if(c.whtr){n++;pts+=c.whtr<.5&&c.whtr>=.4?100:c.whtr<.6?60:30} if(c.whr){n++;const l=state.profile.sex==='male'?.9:.85;pts+=c.whr<l?100:55} if(m.waist){n++;pts+=waistStatus(+m.waist)[1]==='good'?100:waistStatus(+m.waist)[1]==='warn'?60:30} return n?Math.round(pts/n):null}
function infoBtn(key){return `<button class="info-btn" data-info="${key}">הסבר</button>`}
function bindInfo(){document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>showInfo(b.dataset.info))}
function showInfo(key){const i=INFO[key];if(!i)return;const s=SOURCES[i.source];q('dialogTitle').textContent=i.title;q('dialogBody').innerHTML=`<div class="explain-block"><span class="evidence-chip">${i.strength}</span><h3>איך מחושב?</h3><p>${i.formula}</p><h3>מה זה אומר?</h3><p>${i.meaning}</p><h3>מה כדאי לעשות כדי לשפר?</h3><p>${i.improve}</p><h3>מקור מקצועי</h3><p><a href="${s.url}" target="_blank" rel="noopener">${s.name}</a></p></div>`;q('metricDialog').showModal()}
function weeklyActivity(){const cut=new Date();cut.setDate(cut.getDate()-6);const ds=[...Array(7)].map((_,i)=>{const d=new Date(cut);d.setDate(cut.getDate()+i);return d.toISOString().slice(0,10)});const a=state.activities.filter(x=>ds.includes(x.date));return {minutes:sum(a,'minutes'),strength:a.filter(x=>x.type==='כוח').length,count:a.length}}
function actionPlan(){const m=latestMetric(),c=calc(m),h=latestHealth(),a=weeklyActivity(),out=[];if(c.whtr>=.5||bmiStatus(c.bmi)[1]==='warn'||bmiStatus(c.bmi)[1]==='bad')out.push({t:'הפחתה מתונה של שומן בטני',x:'התמקד במגמת משקל והיקף מותניים, לא בירידה מהירה.',k:'weighttrend'});if(a.minutes<150)out.push({t:'להשלים פעילות שבועית',x:`נצברו ${a.minutes} דקות ב-7 הימים האחרונים; יעד בסיסי הוא לפחות 150 דקות מתונות.`,k:'activity'});if(a.strength<2)out.push({t:'להוסיף אימוני כוח',x:`נרשמו ${a.strength} אימוני כוח ב-7 ימים; יעד כללי: לפחות 2 ימים.`,k:'activity'});if(h.sbp>=130||h.dbp>=80)out.push({t:'לשפר ולעקוב אחר לחץ הדם',x:'בצע סדרת מדידות ביתיות בתנאים אחידים ופעל על משקל, פעילות ותזונה.',k:'bp'});if(+h.hba1c>=5.7||+h.fastingGlucose>=100)out.push({t:'מיקוד בבריאות מטבולית',x:'פעילות, ירידה מתונה במשקל ואיכות תזונה הן מנופים מרכזיים; ערכים חריגים דורשים פרשנות רפואית.',k:h.hba1c?'a1c':'glucose'});if(!out.length)out.push({t:'לשמר עקביות',x:'הנתונים שהוזנו אינם מצביעים כרגע על יעד אורח־חיים בולט. המשך מעקב אחר מגמות.',k:'activity'});return out.slice(0,3)}
function renderActions(){const arr=actionPlan();q('nextBestAction').textContent=arr[0].t;q('nextBestActionText').textContent=arr[0].x;q('actionList').innerHTML=arr.map((x,i)=>`<div class="action-item"><span class="action-rank">${i+1}</span><div><strong>${x.t}</strong><div class="sub">${x.x}</div></div>${infoBtn(x.k)}</div>`).join('')}
function renderEvidence(){q('evidenceList').innerHTML=Object.entries(SOURCES).map(([k,s])=>`<a class="source-card" href="${s.url}" target="_blank" rel="noopener"><strong>${s.name}</strong><span>מקור חיצוני רשמי ↗</span></a>`).join('')}
function renderAll(){renderToday();renderActions();renderMetrics();renderMeals();renderActivities();renderHealth();renderReports();renderEvidence();fillSettings();bindInfo()}
function renderToday(){const m=latestMetric(),c=calc(m),sc=score();q('todayWeight').textContent=m.weight?`${(+m.weight).toFixed(1)} ק״ג`:'—';q('goalWeight').textContent=`${state.profile.targetWeight||'—'} ק״ג`;
 const first=state.metrics[0]?.weight;if(m.weight&&first&&state.profile.targetWeight){const p=Math.max(0,Math.min(100,(first-m.weight)/(first-state.profile.targetWeight)*100));q('goalProgress').style.width=p+'%';q('weightDelta').textContent=`${(first-m.weight).toFixed(1)} ק״ג שינוי מתחילת המעקב`}else q('goalProgress').style.width='0%';
 metric('mBMI',c.bmi?.toFixed(1),bmiStatus(c.bmi));metric('mWHtR',c.whtr?.toFixed(2),whtrStatus(c.whtr));metric('mWHR',c.whr?.toFixed(2),whrStatus(c.whr));metric('mWaist',m.waist?`${m.waist} ס״מ`:'—',waistStatus(+m.waist));
 q('healthScore').textContent=sc??'—';const hc=document.querySelector('.health-card');hc.className='card health-card '+(sc==null?'':sc>=85?'good':sc>=60?'warn':'bad');q('overallStatus').textContent=sc==null?'נדרשים נתונים':sc>=85?'מצב טוב':sc>=60?'יש מדדים לשיפור':'נדרש שיפור';q('overallText').textContent=sc==null?'הזן גיל, מין, גובה, משקל והיקפים כדי לקבל תמונת מצב.':`הציון מסכם מדדי גוף בלבד ואינו תחליף להערכת סיכון רפואית מלאה. גיל: ${age()??'לא הוגדר'}.`;
 const h=latestHealth(),ch=calcHealth(h);q('homeBP').textContent=h.sbp&&h.dbp?`${h.sbp}/${h.dbp}`:'—';q('homeBPStatus').textContent=bpStatus(h.sbp,h.dbp)[0];q('homeA1c').textContent=h.hba1c?`${h.hba1c}%`:'—';q('homeLDL').textContent=h.ldl?`${h.ldl}`:'—';q('homeNonHDL').textContent=ch.nonHdl!=null?Math.round(ch.nonHdl):'—';
 const td=today(),meals=state.meals.filter(x=>x.date===td),acts=state.activities.filter(x=>x.date===td),eaten=sum(meals,'calories'),prot=sum(meals,'protein'),burn=sum(acts,'calories'),target=+state.profile.calorieTarget||0,rem=target-eaten,net=eaten-burn;q('calTarget').textContent=target;q('calEaten').textContent=eaten;q('calBurned').textContent=burn;q('calNet').textContent=net;q('calorieRemaining').textContent=rem;const pct=target?Math.min(100,eaten/target*100):0;q('calorieRing').style.background=`conic-gradient(#111827 ${pct}%,#e8eaee ${pct}%)`;const pt=+state.profile.proteinTarget||0,pp=pt?Math.min(100,prot/pt*100):0;q('proteinProgress').style.width=pp+'%';q('proteinPct').textContent=Math.round(pp)+'%';q('proteinText').textContent=`${prot} / ${pt} גרם`}
function metric(id,val,st){q(id).textContent=val??'—';q(id+'Status').textContent=st[0]}
function renderMetrics(){const m=latestMetric();q('inWeight').value=m.weight||'';q('inWaist').value=m.waist||'';q('inHip').value=m.hip||'';q('inBodyFat').value=m.bodyFat||'';const c=calc(m);q('targetsTable').innerHTML=targetRows(c,m);drawChart()}
function targetRows(c,m){const rows=[['BMI',c.bmi?.toFixed(1)||'—','18.5–24.9',bmiStatus(c.bmi)[0],'bmi'],['מותניים/גובה',c.whtr?.toFixed(2)||'—','<0.50',whtrStatus(c.whtr)[0],'whtr'],['מותניים/ירכיים',c.whr?.toFixed(2)||'—',state.profile.sex==='male'?'<0.90':'<0.85',whrStatus(c.whr)[0],'whr'],['היקף מותניים',m.waist?m.waist+' ס״מ':'—',state.profile.sex==='male'?'<94 ס״מ':'<80 ס״מ',waistStatus(+m.waist)[0],'waist'],['אחוז שומן',m.bodyFat?m.bodyFat+'%':'—','מגמה אישית','למעקב',null]];return rows.map(r=>`<div class="target"><div><strong>${r[0]}</strong><div class="sub">נוכחי: ${r[1]}</div></div><div class="target-side"><span class="badge">יעד ${r[2]}</span><div class="sub">${r[3]}</div>${r[4]?infoBtn(r[4]):''}</div></div>`).join('')}
function drawChart(){const c=q('weightChart'),ctx=c.getContext('2d'),d=[...state.metrics].sort((a,b)=>a.date.localeCompare(b.date)).slice(-30);const w=c.width=c.clientWidth*devicePixelRatio,h=c.height=180*devicePixelRatio;ctx.clearRect(0,0,w,h);if(d.length<2){ctx.fillStyle='#6b7280';ctx.font=`${14*devicePixelRatio}px Arial`;ctx.fillText('נדרשות לפחות שתי שקילות',20*devicePixelRatio,90*devicePixelRatio);return}const vals=d.map(x=>+x.weight).filter(Boolean),min=Math.min(...vals)-1,max=Math.max(...vals)+1;ctx.strokeStyle='#111827';ctx.lineWidth=2*devicePixelRatio;ctx.beginPath();d.forEach((x,i)=>{const xx=(i/(d.length-1))*w,yy=h-((x.weight-min)/(max-min))*h;(i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy))});ctx.stroke()}
function renderMeals(){const arr=state.meals.filter(x=>x.date===today()).sort((a,b)=>b.time.localeCompare(a.time));q('mealList').innerHTML=arr.length?arr.map(x=>`<div class="listitem"><div><strong>${x.desc||'ארוחה'}</strong><div class="sub">${x.time}</div></div><div>${x.calories} קק״ל<br><span class="sub">${x.protein||0} ג׳ חלבון</span></div></div>`).join(''):'<div class="sub">אין ארוחות להיום</div>'}
function renderActivities(){const arr=state.activities.filter(x=>x.date===today()).sort((a,b)=>b.time.localeCompare(a.time));q('activityList').innerHTML=arr.length?arr.map(x=>`<div class="listitem"><div><strong>${x.type}</strong><div class="sub">${x.minutes||0} דקות</div></div><div>${x.calories||0} קק״ל</div></div>`).join(''):'<div class="sub">אין פעילות להיום</div>'}
function renderHealth(){const h=latestHealth(),c=calcHealth(h);['sbp','dbp','restingHr','totalChol','ldl','hdl','triglycerides','fastingGlucose','hba1c','egfr','creatinine','uacr','apoB','lpa','prevent10','prevent30'].forEach(k=>{const el=q('h_'+k);if(el)el.value=h[k]??''});q('h_smoking').checked=!!h.smoking;q('h_diabetes').checked=!!h.diabetes;q('h_bpMeds').checked=!!h.bpMeds;
 q('healthDerived').innerHTML=[['לחץ דם',h.sbp&&h.dbp?`${h.sbp}/${h.dbp} mmHg`:'—','<120/80',bpStatus(h.sbp,h.dbp)[0],'bp'],['דופק מנוחה',h.restingHr?`${h.restingHr} פעימות/דק׳`:'—','מגמה אישית','למעקב'],['HbA1c',h.hba1c?`${h.hba1c}%`:'—','<5.7% ללא סוכרת',a1cStatus(h.hba1c)[0],'a1c'],['גלוקוז בצום',h.fastingGlucose?`${h.fastingGlucose} mg/dL`:'—','<100',glucoseStatus(h.fastingGlucose)[0],'glucose'],['LDL-C',h.ldl?`${h.ldl} mg/dL`:'—','תלוי רמת סיכון',ldlStatus(h.ldl)[0],'ldl'],['Non-HDL-C',c.nonHdl!=null?`${Math.round(c.nonHdl)} mg/dL`:'—','תלוי רמת סיכון','מחושב אוטומטית','nonhdl'],['טריגליצרידים',h.triglycerides?`${h.triglycerides} mg/dL`:'—','<150',tgStatus(h.triglycerides)[0],'tg'],['TG/HDL',c.tgHdl!=null?c.tgHdl.toFixed(2):'—','מדד משלים','ללא סף אבחנתי יחיד','tghdl'],['Pulse Pressure',c.pulsePressure!=null?`${Math.round(c.pulsePressure)} mmHg`:'—','מגמה','מחושב'],['MAP',c.map!=null?`${Math.round(c.map)} mmHg`:'—','מגמה','מחושב'],['eGFR',h.egfr?`${h.egfr} mL/min/1.73m²`:'—','פענוח רפואי','כליה','egfr'],['UACR',h.uacr?`${h.uacr} mg/g`:'—','פענוח רפואי','כליה','uacr'],['ApoB',h.apoB?`${h.apoB} mg/dL`:'—','תלוי סיכון','מתקדם'],['Lp(a)',h.lpa?`${h.lpa} mg/dL`:'—','לפי מעבדה/הנחיה','מתקדם']].map(r=>`<div class="target"><div><strong>${r[0]}</strong><div class="sub">נוכחי: ${r[1]}</div></div><div class="target-side"><span class="badge">יעד ${r[2]}</span><div class="sub">${r[3]}</div>${r[4]?infoBtn(r[4]):''}</div></div>`).join('');
 const a=age();let eligibility='נדרשים גיל ונתוני בריאות';if(a!=null){if(a>=30&&a<=79)eligibility='מתאים עקרונית לחישוב PREVENT ל־10 שנים, בכפוף לקריטריונים הקליניים';else eligibility='מחוץ לטווח הגיל המקובל של PREVENT ל־10 שנים';if(a>=30&&a<=59)eligibility+='; ניתן גם לחשב סיכון ל־30 שנה'}q('preventEligibility').textContent=eligibility;q('preventStored').textContent=`10 שנים: ${h.prevent10?`${h.prevent10}%`:'—'} | 30 שנים: ${h.prevent30?`${h.prevent30}%`:'—'}`;
 const hist=[...state.health].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);q('healthHistory').innerHTML=hist.length?hist.map(x=>`<div class="listitem"><div><strong>${x.date}</strong><div class="sub">לחץ דם ${x.sbp&&x.dbp?`${x.sbp}/${x.dbp}`:'—'} | HbA1c ${x.hba1c||'—'}%</div></div><div>${x.ldl?`LDL ${x.ldl}`:''}</div></div>`).join(''):'<div class="sub">עדיין אין מדידות בריאות שמורות</div>'}
function renderReports(){const cut=new Date();cut.setDate(cut.getDate()-6);const ds=[...Array(7)].map((_,i)=>{const d=new Date(cut);d.setDate(cut.getDate()+i);return d.toISOString().slice(0,10)});const ms=state.metrics.filter(x=>ds.includes(x.date));const meals=state.meals.filter(x=>ds.includes(x.date));const acts=state.activities.filter(x=>ds.includes(x.date));const avg=ms.length?(sum(ms,'weight')/ms.length).toFixed(1):'—';const h=latestHealth(),ch=calcHealth(h);q('weeklySummary').innerHTML=`<div class="targets"><div class="target"><strong>משקל ממוצע</strong><span>${avg} ק״ג</span></div><div class="target"><strong>קלוריות ממוצעות</strong><span>${Math.round(sum(meals,'calories')/7)}</span></div><div class="target"><strong>חלבון ממוצע</strong><span>${Math.round(sum(meals,'protein')/7)} ג׳</span></div><div class="target"><strong>פעילות</strong><span>${acts.length} אימונים</span></div><div class="target"><strong>לחץ דם אחרון</strong><span>${h.sbp&&h.dbp?`${h.sbp}/${h.dbp}`:'—'}</span></div><div class="target"><strong>Non-HDL אחרון</strong><span>${ch.nonHdl!=null?Math.round(ch.nonHdl):'—'}</span></div></div>`;q('reportTargets').innerHTML=targetRows(calc(),latestMetric())}
function fillSettings(){const p=state.profile;q('birthDate').value=p.birthDate||'';q('sex').value=p.sex||'male';q('height').value=p.height||'';q('targetWeight').value=p.targetWeight||'';q('calorieTarget').value=p.calorieTarget||'';q('proteinTarget').value=p.proteinTarget||''}
function q(id){return document.getElementById(id)}function sum(a,k){return a.reduce((s,x)=>s+(+x[k]||0),0)}
function validScreen(name){return ['today','meals','metrics','activity','health','reports','evidence','settings'].includes(name)}
function go(name,updateHash=true){if(!validScreen(name))name='today';document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));document.querySelectorAll('[data-screen-btn]').forEach(x=>x.classList.toggle('active',x.dataset.screenBtn===name));q('pageTitle').textContent={today:'היום',meals:'ארוחות',metrics:'מדדי גוף',activity:'פעילות',health:'בריאות',reports:'דוחות',evidence:'ידע ומקורות',settings:'הגדרות'}[name]||'';if(updateHash&&location.hash!==`#${name}`){history.replaceState(null,'',`#${name}`)}scrollTo(0,0)}
document.querySelectorAll('[data-screen-btn]').forEach(b=>b.onclick=()=>go(b.dataset.screenBtn));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));q('settingsBtn').onclick=()=>go('settings');
q('saveSettings').onclick=()=>{state.profile={birthDate:q('birthDate').value,sex:q('sex').value,height:+q('height').value,targetWeight:+q('targetWeight').value,calorieTarget:+q('calorieTarget').value,proteinTarget:+q('proteinTarget').value};save();go('today')};
q('saveMetrics').onclick=()=>{const rec={date:today(),weight:+q('inWeight').value,waist:+q('inWaist').value,hip:+q('inHip').value,bodyFat:+q('inBodyFat').value};state.metrics=state.metrics.filter(x=>x.date!==rec.date);state.metrics.push(rec);save();go('today')};
q('saveMeal').onclick=()=>{state.meals.push({id:Date.now(),date:today(),time:new Date().toTimeString().slice(0,5),desc:q('mealDesc').value,calories:+q('mealCalories').value||0,protein:+q('mealProtein').value||0});q('mealDesc').value='';q('mealCalories').value='';q('mealProtein').value='';save()};
q('saveActivity').onclick=()=>{state.activities.push({id:Date.now(),date:today(),time:new Date().toTimeString().slice(0,5),type:q('actType').value,minutes:+q('actMinutes').value||0,calories:+q('actCalories').value||0});q('actMinutes').value='';q('actCalories').value='';save()};
q('saveHealth').onclick=()=>{const keys=['sbp','dbp','restingHr','totalChol','ldl','hdl','triglycerides','fastingGlucose','hba1c','egfr','creatinine','uacr','apoB','lpa','prevent10','prevent30'];const rec={date:q('healthDate').value||today()};keys.forEach(k=>rec[k]=+q('h_'+k).value||'');rec.smoking=q('h_smoking').checked;rec.diabetes=q('h_diabetes').checked;rec.bpMeds=q('h_bpMeds').checked;state.health=state.health.filter(x=>x.date!==rec.date);state.health.push(rec);save()};
q('healthDate').value=today();
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});renderAll();const initialScreen=(location.hash||'#today').replace('#','');go(validScreen(initialScreen)?initialScreen:'today',false);window.addEventListener('hashchange',()=>{const s=(location.hash||'#today').replace('#','');if(validScreen(s))go(s,false)});
