const LS='weightHealthPWA_v1';
const LS_BACKUP='weightHealthPWA_v1_backup';
const LS_PREVIOUS='weightHealthPWA_v1_previous';
const today=()=>new Date().toISOString().slice(0,10);
const defaultState={profile:{birthDate:'',sex:'male',height:192,targetWeight:92,calorieTarget:1850,proteinTarget:150,weeklyActivityTarget:150},metrics:[],meals:[],activities:[],health:[]};
function safeParse(raw){try{return raw?JSON.parse(raw):null}catch(e){return null}}
function hasUserData(s){return !!(s&&((s.metrics&&s.metrics.length)||(s.meals&&s.meals.length)||(s.activities&&s.activities.length)||(s.health&&s.health.length)||(s.profile&&s.profile.birthDate)))}
function loadState(){
  const candidates=[LS,LS_BACKUP,LS_PREVIOUS,'dietControlData','weightHealthPWA_v2'];
  for(const key of candidates){const parsed=safeParse(localStorage.getItem(key));if(hasUserData(parsed))return parsed}
  return safeParse(localStorage.getItem(LS))||defaultState;
}
let state=loadState();
state.profile={...defaultState.profile,...(state.profile||{})};
state.metrics=state.metrics||[];state.meals=state.meals||[];state.activities=state.activities||[];state.health=state.health||[];
function save(){const previous=localStorage.getItem(LS);if(previous)localStorage.setItem(LS_PREVIOUS,previous);const raw=JSON.stringify(state);localStorage.setItem(LS,raw);localStorage.setItem(LS_BACKUP,raw);renderAll()}
function age(){if(!state.profile.birthDate)return null;const b=new Date(state.profile.birthDate),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n<new Date(n.getFullYear(),b.getMonth(),b.getDate()))a--;return a}
function latestMetric(){return [...state.metrics].sort((a,b)=>a.date.localeCompare(b.date)).at(-1)||{}}
function latestHealth(){return [...state.health].sort((a,b)=>a.date.localeCompare(b.date)).at(-1)||{}}
function calc(m=latestMetric()){
 const h=+state.profile.height||0,w=+m.weight||0,wa=+m.waist||0,hip=+m.hip||0;
 const bmi=h&&w?w/((h/100)**2):null, whtr=h&&wa?wa/h:null,whr=wa&&hip?wa/hip:null;
 return {bmi,whtr,whr};
}
function calcHealth(h=latestHealth()){
 const tc=+h.totalChol||0,hdl=+h.hdl||0,tg=+h.triglycerides||0,sbp=+h.sbp||0,dbp=+h.dbp||0;
 return {nonHdl:tc&&hdl?tc-hdl:null,tgHdl:tg&&hdl?tg/hdl:null,pulsePressure:sbp&&dbp?sbp-dbp:null,map:sbp&&dbp?dbp+(sbp-dbp)/3:null};
}
function bmiStatus(v){if(v==null)return['—','']; if(v<18.5)return['נמוך','warn'];if(v<25)return['טווח תקין','good'];if(v<30)return['עודף משקל','warn'];return['השמנה','bad']}
function whtrStatus(v){if(v==null)return['—',''];if(v<.4)return['נמוך','warn'];if(v<.5)return['יעד מועדף','good'];if(v<.6)return['סיכון מוגבר','warn'];return['סיכון גבוה','bad']}
function whrStatus(v){if(v==null)return['—',''];const lim=state.profile.sex==='male'?.90:.85;return v<lim?['מתחת לסף','good']:['מעל הסף','warn']}
function waistStatus(v){if(!v)return['—',''];const s=state.profile.sex==='male';const warn=s?94:80,high=s?102:88;if(v<warn)return['מתחת לסף פעולה','good'];if(v<high)return['מוגבר','warn'];return['גבוה','bad']}
function bpStatus(s,d){s=+s;d=+d;if(!s||!d)return['—',''];if(s<120&&d<80)return['תקין','good'];if(s<130&&d<80)return['מוגבר','warn'];if(s<140&&d<90)return['יתר לחץ דם דרגה 1','warn'];if(s>=180||d>=120)return['ערך חמור — נדרשת הערכה רפואית','bad'];return['יתר לחץ דם דרגה 2','bad']}
function a1cStatus(v){v=+v;if(!v)return['—',''];if(v<5.7)return['בטווח תקין','good'];if(v<6.5)return['טווח טרום־סוכרת','warn'];return['בטווח אבחנתי לסוכרת*','bad']}
function glucoseStatus(v){v=+v;if(!v)return['—',''];if(v<100)return['בטווח תקין','good'];if(v<126)return['טווח טרום־סוכרת','warn'];return['בטווח אבחנתי לסוכרת*','bad']}
function tgStatus(v){v=+v;if(!v)return['—',''];if(v<150)return['תקין','good'];if(v<200)return['גבולי','warn'];if(v<500)return['גבוה','bad'];return['גבוה מאוד','bad']}
function ldlStatus(v){v=+v;if(!v)return['—',''];if(v<100)return['נמוך יחסית','good'];if(v<130)return['קרוב לטווח המקובל','warn'];if(v<160)return['מוגבר','warn'];return['גבוה','bad']}
function score(){const m=latestMetric(),c=calc(m);let pts=0,n=0; if(c.bmi){n++;pts+=c.bmi>=18.5&&c.bmi<25?100:c.bmi<30?65:35} if(c.whtr){n++;pts+=c.whtr<.5&&c.whtr>=.4?100:c.whtr<.6?60:30} if(c.whr){n++;const l=state.profile.sex==='male'?.9:.85;pts+=c.whr<l?100:55} if(m.waist){n++;pts+=waistStatus(+m.waist)[1]==='good'?100:waistStatus(+m.waist)[1]==='warn'?60:30} return n?Math.round(pts/n):null}
function renderAll(){renderToday();renderMetrics();renderMeals();renderActivities();renderHealth();renderReports();fillSettings()}
function renderToday(){const m=latestMetric(),c=calc(m),sc=score();q('todayWeight').textContent=m.weight?`${(+m.weight).toFixed(1)} ק״ג`:'—';q('goalWeight').textContent=`${state.profile.targetWeight||'—'} ק״ג`;
 const first=state.metrics[0]?.weight;if(m.weight&&first&&state.profile.targetWeight){const p=Math.max(0,Math.min(100,(first-m.weight)/(first-state.profile.targetWeight)*100));q('goalProgress').style.width=p+'%';q('weightDelta').textContent=`${(first-m.weight).toFixed(1)} ק״ג שינוי מתחילת המעקב`}else q('goalProgress').style.width='0%';
 metric('mBMI',c.bmi?.toFixed(1),bmiStatus(c.bmi));metric('mWHtR',c.whtr?.toFixed(2),whtrStatus(c.whtr));metric('mWHR',c.whr?.toFixed(2),whrStatus(c.whr));metric('mWaist',m.waist?`${m.waist} ס״מ`:'—',waistStatus(+m.waist));
 q('healthScore').textContent=sc??'—';const hc=document.querySelector('.health-card');hc.className='card health-card '+(sc==null?'':sc>=85?'good':sc>=60?'warn':'bad');q('overallStatus').textContent=sc==null?'נדרשים נתונים':sc>=85?'מצב טוב':sc>=60?'יש מדדים לשיפור':'נדרש שיפור';q('overallText').textContent=sc==null?'הזן גיל, מין, גובה, משקל והיקפים כדי לקבל תמונת מצב.':`הציון מסכם מדדי גוף בלבד ואינו תחליף להערכת סיכון רפואית מלאה. גיל: ${age()??'לא הוגדר'}.`;
 const h=latestHealth(),ch=calcHealth(h);q('homeBP').textContent=h.sbp&&h.dbp?`${h.sbp}/${h.dbp}`:'—';q('homeBPStatus').textContent=bpStatus(h.sbp,h.dbp)[0];q('homeA1c').textContent=h.hba1c?`${h.hba1c}%`:'—';q('homeLDL').textContent=h.ldl?`${h.ldl}`:'—';q('homeNonHDL').textContent=ch.nonHdl!=null?Math.round(ch.nonHdl):'—';
 const td=today(),meals=state.meals.filter(x=>x.date===td),acts=state.activities.filter(x=>x.date===td),eaten=sum(meals,'calories'),prot=sum(meals,'protein'),burn=sum(acts,'calories'),target=+state.profile.calorieTarget||0,rem=target-eaten,net=eaten-burn;q('calTarget').textContent=target;q('calEaten').textContent=eaten;q('calBurned').textContent=burn;q('calNet').textContent=net;q('calorieRemaining').textContent=rem;['mealCalTarget','mealCalEaten','mealCalBurned','mealCalNet','mealCalorieRemaining'].forEach((id,i)=>{const vals=[target,eaten,burn,net,rem];const el=q(id);if(el)el.textContent=vals[i]});const pct=target?Math.min(100,eaten/target*100):0;const ringColor=eaten>target?'#dc2626':pct>=85?'#f59e0b':'#2563eb';const ringBg=`conic-gradient(${ringColor} ${pct}%,#e5e7eb ${pct}%)`;q('calorieRing').style.background=ringBg;if(q('mealCalorieRing'))q('mealCalorieRing').style.background=ringBg;if(q('mealCalorieStatus')){q('mealCalorieStatus').textContent=rem>=0?`נותרו ${rem} קק״ל`:`חריגה ${Math.abs(rem)} קק״ל`;q('mealCalorieStatus').className='calorie-status '+(rem<0?'over':rem<target*.15?'near':'ok')}const pt=+state.profile.proteinTarget||0,pp=pt?Math.min(100,prot/pt*100):0;q('proteinProgress').style.width=pp+'%';q('proteinPct').textContent=Math.round(pp)+'%';q('proteinText').textContent=`${prot} / ${pt} גרם`}
function metric(id,val,st){q(id).textContent=val??'—';q(id+'Status').textContent=st[0]}
function renderMetrics(){const m=latestMetric();q('inWeight').value=m.weight||'';q('inWaist').value=m.waist||'';q('inHip').value=m.hip||'';q('inBodyFat').value=m.bodyFat||'';const c=calc(m);q('targetsTable').innerHTML=targetRows(c,m);drawChart()}
function targetRows(c,m){const rows=[['BMI',c.bmi?.toFixed(1)||'—','18.5–24.9',bmiStatus(c.bmi)[0]],['מותניים/גובה',c.whtr?.toFixed(2)||'—','0.40–0.49',whtrStatus(c.whtr)[0]],['מותניים/ירכיים',c.whr?.toFixed(2)||'—',state.profile.sex==='male'?'<0.90':'<0.85',whrStatus(c.whr)[0]],['היקף מותניים',m.waist?m.waist+' ס״מ':'—',state.profile.sex==='male'?'<94 ס״מ':'<80 ס״מ',waistStatus(+m.waist)[0]],['אחוז שומן',m.bodyFat?m.bodyFat+'%':'—','מותאם גיל/מין','למעקב']];return rows.map(r=>`<div class="target"><div><strong>${r[0]}</strong><div class="sub">נוכחי: ${r[1]}</div></div><div style="text-align:left"><span class="badge">יעד ${r[2]}</span><div class="sub">${r[3]}</div></div></div>`).join('')}
function drawChart(){const c=q('weightChart'),ctx=c.getContext('2d'),d=[...state.metrics].sort((a,b)=>a.date.localeCompare(b.date)).slice(-30);const w=c.width=c.clientWidth*devicePixelRatio,h=c.height=180*devicePixelRatio;ctx.clearRect(0,0,w,h);if(d.length<2){ctx.fillStyle='#6b7280';ctx.font=`${14*devicePixelRatio}px Arial`;ctx.fillText('נדרשות לפחות שתי שקילות',20*devicePixelRatio,90*devicePixelRatio);return}const vals=d.map(x=>+x.weight).filter(Boolean),min=Math.min(...vals)-1,max=Math.max(...vals)+1;ctx.strokeStyle='#111827';ctx.lineWidth=2*devicePixelRatio;ctx.beginPath();d.forEach((x,i)=>{const xx=(i/(d.length-1))*w,yy=h-((x.weight-min)/(max-min))*h;(i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy))});ctx.stroke()}
function renderMeals(){const arr=state.meals.filter(x=>x.date===today()).sort((a,b)=>b.time.localeCompare(a.time));q('mealList').innerHTML=arr.length?arr.map(x=>`<div class="listitem"><div><strong>${x.desc||'ארוחה'}</strong><div class="sub">${x.time}</div></div><div>${x.calories} קק״ל<br><span class="sub">${x.protein||0} ג׳ חלבון</span></div></div>`).join(''):'<div class="sub">אין ארוחות להיום</div>'}
function getLast7Days(){const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-i);days.push(d.toISOString().slice(0,10))}return days}
function renderActivities(){
 const todayKey=today();
 const todayArr=state.activities.filter(x=>x.date===todayKey).sort((a,b)=>b.time.localeCompare(a.time));
 q('activityList').innerHTML=todayArr.length?todayArr.map(x=>`<div class="listitem"><div><strong>${x.type}</strong><div class="sub">${x.minutes||0} דקות</div></div><div>${x.calories||0} קק״ל</div></div>`).join(''):'<div class="sub">אין פעילות להיום</div>';
 const days=[]; const now=new Date();
 for(let i=6;i>=0;i--){const d=new Date(now);d.setDate(now.getDate()-i);days.push(d.toISOString().slice(0,10))}
 const week=state.activities.filter(x=>days.includes(x.date));
 const mins=sum(week,'minutes'), calories=sum(week,'calories'), count=week.length;
 const target=+(state.profile.activityTarget||150); const remain=Math.max(0,target-mins); const pct=target?Math.min(100,mins/target*100):0;
 q('weekActivityTarget').textContent=target; q('weekActivityMinutes').textContent=mins; q('weekActivityCalories').textContent=calories; q('weekActivityCount').textContent=count; q('activityRingValue').textContent=remain;
 const ring=q('activityRing'); if(ring)ring.style.background=`conic-gradient(#16a34a ${pct}%,#e8eaee ${pct}%)`;
 const status=q('activityWeekStatus'); const txt=q('activityProgressText');
 if(mins>=target){status.textContent='היעד הושג';status.className='calorie-status good';txt.textContent=`מצוין — השלמת ${mins} דקות פעילות השבוע`}
 else if(mins>=target*.75){status.textContent='קרוב ליעד';status.className='calorie-status warning';txt.textContent=`נותרו עוד ${remain} דקות להשלמת היעד השבועי`}
 else{status.textContent='בתהליך';status.className='calorie-status ok';txt.textContent=`בוצעו ${mins} מתוך ${target} דקות — נותרו ${remain}`}
 const totalCount=state.activities.length,totalMinutes=sum(state.activities,'minutes'),totalCalories=sum(state.activities,'calories');q('totalActivityCount').textContent=totalCount;q('totalActivityMinutes').textContent=totalMinutes;q('totalActivityCalories').textContent=totalCalories;
 const avg=count?Math.round(mins/7):0;q('activityWeekAverage').textContent=`ממוצע: ${avg} דק׳ ליום`;
 drawActivityChart(days);
}
function drawActivityChart(days){
 const c=q('activityChart'); if(!c)return; const ctx=c.getContext('2d'); const ratio=window.devicePixelRatio||1; const cssW=Math.max(300,c.clientWidth||320),cssH=230;c.width=cssW*ratio;c.height=cssH*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,cssW,cssH);
 const vals=days.map(d=>sum(state.activities.filter(x=>x.date===d),'minutes')); const max=Math.max(30,...vals); const left=30,right=10,top=18,bottom=42,plotW=cssW-left-right,plotH=cssH-top-bottom,slot=plotW/7,barW=Math.min(34,slot*.58);
 ctx.strokeStyle='#d1d5db';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(left,top+plotH);ctx.lineTo(cssW-right,top+plotH);ctx.stroke();
 const heb=['א׳','ב׳','ג׳','ד׳','ה׳','ו׳','ש׳'];
 vals.forEach((v,i)=>{const h=(v/max)*plotH,x=left+i*slot+(slot-barW)/2,y=top+plotH-h;ctx.fillStyle=v?'#16a34a':'#e5e7eb';ctx.beginPath();ctx.roundRect(x,y,barW,Math.max(3,h),8);ctx.fill();ctx.fillStyle='#374151';ctx.font='12px Arial';ctx.textAlign='center';ctx.fillText(String(v),x+barW/2,Math.max(12,y-6));const dt=new Date(days[i]+'T12:00:00');ctx.fillStyle='#6b7280';ctx.fillText(heb[dt.getDay()],x+barW/2,top+plotH+18);ctx.font='10px Arial';ctx.fillText(days[i].slice(5).replace('-','/'),x+barW/2,top+plotH+32)});
}
function renderHealth(){const h=latestHealth(),c=calcHealth(h);['sbp','dbp','restingHr','totalChol','ldl','hdl','triglycerides','fastingGlucose','hba1c','egfr','creatinine','uacr','apoB','lpa','prevent10','prevent30'].forEach(k=>{const el=q('h_'+k);if(el)el.value=h[k]??''});q('h_smoking').checked=!!h.smoking;q('h_diabetes').checked=!!h.diabetes;q('h_bpMeds').checked=!!h.bpMeds;
 q('healthDerived').innerHTML=[['לחץ דם',h.sbp&&h.dbp?`${h.sbp}/${h.dbp} mmHg`:'—','<120/80',bpStatus(h.sbp,h.dbp)[0]],['דופק מנוחה',h.restingHr?`${h.restingHr} פעימות/דק׳`:'—','מגמה אישית','למעקב'],['HbA1c',h.hba1c?`${h.hba1c}%`:'—','<5.7% ללא סוכרת',a1cStatus(h.hba1c)[0]],['גלוקוז בצום',h.fastingGlucose?`${h.fastingGlucose} mg/dL`:'—','<100',glucoseStatus(h.fastingGlucose)[0]],['LDL-C',h.ldl?`${h.ldl} mg/dL`:'—','תלוי רמת סיכון',ldlStatus(h.ldl)[0]],['Non-HDL-C',c.nonHdl!=null?`${Math.round(c.nonHdl)} mg/dL`:'—','תלוי רמת סיכון','מחושב אוטומטית'],['טריגליצרידים',h.triglycerides?`${h.triglycerides} mg/dL`:'—','<150',tgStatus(h.triglycerides)[0]],['TG/HDL',c.tgHdl!=null?c.tgHdl.toFixed(2):'—','מדד משלים','ללא סף אבחנתי יחיד'],['Pulse Pressure',c.pulsePressure!=null?`${Math.round(c.pulsePressure)} mmHg`:'—','מגמה','מחושב'],['MAP',c.map!=null?`${Math.round(c.map)} mmHg`:'—','מגמה','מחושב'],['eGFR',h.egfr?`${h.egfr} mL/min/1.73m²`:'—','פענוח רפואי','כליה'],['UACR',h.uacr?`${h.uacr} mg/g`:'—','פענוח רפואי','כליה'],['ApoB',h.apoB?`${h.apoB} mg/dL`:'—','תלוי סיכון','מתקדם'],['Lp(a)',h.lpa?`${h.lpa} mg/dL`:'—','לפי מעבדה/הנחיה','מתקדם']].map(r=>`<div class="target"><div><strong>${r[0]}</strong><div class="sub">נוכחי: ${r[1]}</div></div><div style="text-align:left"><span class="badge">יעד ${r[2]}</span><div class="sub">${r[3]}</div></div></div>`).join('');
 const a=age();let eligibility='נדרשים גיל ונתוני בריאות';if(a!=null){if(a>=30&&a<=79)eligibility='מתאים עקרונית לחישוב PREVENT ל־10 שנים, בכפוף לקריטריונים הקליניים';else eligibility='מחוץ לטווח הגיל המקובל של PREVENT ל־10 שנים';if(a>=30&&a<=59)eligibility+='; ניתן גם לחשב סיכון ל־30 שנה'}q('preventEligibility').textContent=eligibility;q('preventStored').textContent=`10 שנים: ${h.prevent10?`${h.prevent10}%`:'—'} | 30 שנים: ${h.prevent30?`${h.prevent30}%`:'—'}`;
 const hist=[...state.health].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);q('healthHistory').innerHTML=hist.length?hist.map(x=>`<div class="listitem"><div><strong>${x.date}</strong><div class="sub">לחץ דם ${x.sbp&&x.dbp?`${x.sbp}/${x.dbp}`:'—'} | HbA1c ${x.hba1c||'—'}%</div></div><div>${x.ldl?`LDL ${x.ldl}`:''}</div></div>`).join(''):'<div class="sub">עדיין אין מדידות בריאות שמורות</div>'}
function renderReports(){const cut=new Date();cut.setDate(cut.getDate()-6);const ds=[...Array(7)].map((_,i)=>{const d=new Date(cut);d.setDate(cut.getDate()+i);return d.toISOString().slice(0,10)});const ms=state.metrics.filter(x=>ds.includes(x.date));const meals=state.meals.filter(x=>ds.includes(x.date));const acts=state.activities.filter(x=>ds.includes(x.date));const avg=ms.length?(sum(ms,'weight')/ms.length).toFixed(1):'—';const h=latestHealth(),ch=calcHealth(h);q('weeklySummary').innerHTML=`<div class="targets"><div class="target"><strong>משקל ממוצע</strong><span>${avg} ק״ג</span></div><div class="target"><strong>קלוריות ממוצעות</strong><span>${Math.round(sum(meals,'calories')/7)}</span></div><div class="target"><strong>חלבון ממוצע</strong><span>${Math.round(sum(meals,'protein')/7)} ג׳</span></div><div class="target"><strong>פעילות</strong><span>${acts.length} אימונים</span></div><div class="target"><strong>לחץ דם אחרון</strong><span>${h.sbp&&h.dbp?`${h.sbp}/${h.dbp}`:'—'}</span></div><div class="target"><strong>Non-HDL אחרון</strong><span>${ch.nonHdl!=null?Math.round(ch.nonHdl):'—'}</span></div></div>`;q('reportTargets').innerHTML=targetRows(calc(),latestMetric())}
function fillSettings(){const p=state.profile;q('birthDate').value=p.birthDate||'';q('sex').value=p.sex||'male';q('height').value=p.height||'';q('targetWeight').value=p.targetWeight||'';q('calorieTarget').value=p.calorieTarget||'';q('proteinTarget').value=p.proteinTarget||'';q('weeklyActivityTarget').value=p.weeklyActivityTarget||150}
function q(id){return document.getElementById(id)}function sum(a,k){return a.reduce((s,x)=>s+(+x[k]||0),0)}
function validScreen(name){return ['today','meals','metrics','activity','health','reports','settings'].includes(name)}
function go(name,updateHash=true){if(!validScreen(name))name='today';document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));document.querySelectorAll('[data-screen-btn]').forEach(x=>x.classList.toggle('active',x.dataset.screenBtn===name));q('pageTitle').textContent={today:'היום',meals:'ארוחות',metrics:'מדדי גוף',activity:'פעילות',health:'בריאות',reports:'דוחות',settings:'הגדרות'}[name]||'';if(updateHash&&location.hash!==`#${name}`){history.replaceState(null,'',`#${name}`)}scrollTo(0,0)}
document.querySelectorAll('[data-screen-btn]').forEach(b=>b.onclick=()=>go(b.dataset.screenBtn));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));q('settingsBtn').onclick=()=>go('settings');
q('saveSettings').onclick=()=>{state.profile={birthDate:q('birthDate').value,sex:q('sex').value,height:+q('height').value,targetWeight:+q('targetWeight').value,calorieTarget:+q('calorieTarget').value,proteinTarget:+q('proteinTarget').value,weeklyActivityTarget:+q('weeklyActivityTarget').value||150};save();go('today')};
q('saveMetrics').onclick=()=>{const rec={date:today(),weight:+q('inWeight').value,waist:+q('inWaist').value,hip:+q('inHip').value,bodyFat:+q('inBodyFat').value};state.metrics=state.metrics.filter(x=>x.date!==rec.date);state.metrics.push(rec);save();go('today')};
q('saveMeal').onclick=()=>{state.meals.push({id:Date.now(),date:today(),time:new Date().toTimeString().slice(0,5),desc:q('mealDesc').value,calories:+q('mealCalories').value||0,protein:+q('mealProtein').value||0});q('mealDesc').value='';q('mealCalories').value='';q('mealProtein').value='';save()};
q('saveActivity').onclick=()=>{state.activities.push({id:Date.now(),date:today(),time:new Date().toTimeString().slice(0,5),type:q('actType').value,minutes:+q('actMinutes').value||0,calories:+q('actCalories').value||0});q('actMinutes').value='';q('actCalories').value='';save()};
q('saveHealth').onclick=()=>{const keys=['sbp','dbp','restingHr','totalChol','ldl','hdl','triglycerides','fastingGlucose','hba1c','egfr','creatinine','uacr','apoB','lpa','prevent10','prevent30'];const rec={date:q('healthDate').value||today()};keys.forEach(k=>rec[k]=+q('h_'+k).value||'');rec.smoking=q('h_smoking').checked;rec.diabetes=q('h_diabetes').checked;rec.bpMeds=q('h_bpMeds').checked;state.health=state.health.filter(x=>x.date!==rec.date);state.health.push(rec);save()};
q('exportBackup').onclick=()=>{const payload={app:'Diet Control',version:'3.4',exportedAt:new Date().toISOString(),data:state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`Diet_Control_Backup_${today()}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);q('backupStatus').textContent='קובץ הגיבוי יוצא בהצלחה.'};
q('importBackup').onchange=async e=>{const file=e.target.files&&e.target.files[0];if(!file)return;try{const text=await file.text();const parsed=JSON.parse(text);const incoming=parsed.data||parsed;if(!incoming||typeof incoming!=='object')throw new Error('invalid');if(!confirm('לייבא את הגיבוי ולהחליף את הנתונים הנוכחיים באפליקציה?')){e.target.value='';return}state=incoming;state.profile={...defaultState.profile,...(state.profile||{})};state.metrics=state.metrics||[];state.meals=state.meals||[];state.activities=state.activities||[];state.health=state.health||[];save();q('backupStatus').textContent='הגיבוי יובא בהצלחה.';e.target.value=''}catch(err){q('backupStatus').textContent='לא ניתן לקרוא את קובץ הגיבוי.'}};
q('healthDate').value=today();
let deferredInstallPrompt=window.__dietInstallPrompt||null;const installBtn=q('installBtn');
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function updateInstallButton(){if(!installBtn)return;installBtn.classList.remove('ready','waiting','installed');if(isStandalone()){installBtn.textContent='✓ מותקן';installBtn.classList.add('installed');installBtn.disabled=true}else if(deferredInstallPrompt||window.__dietInstallPrompt){deferredInstallPrompt=deferredInstallPrompt||window.__dietInstallPrompt;installBtn.textContent='⬇ התקן עכשיו';installBtn.classList.add('ready');installBtn.disabled=false}else{installBtn.textContent='⬇ התקנה';installBtn.classList.add('waiting');installBtn.disabled=false}}
window.addEventListener('dietinstallready',()=>{deferredInstallPrompt=window.__dietInstallPrompt;updateInstallButton()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;window.__dietInstallPrompt=e;updateInstallButton()});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;window.__dietInstallPrompt=null;updateInstallButton()});
const installHelp=q('installHelp'),installHelpClose=q('installHelpClose');if(installHelpClose)installHelpClose.onclick=()=>installHelp.hidden=true;if(installHelp)installHelp.onclick=e=>{if(e.target===installHelp)installHelp.hidden=true};
if(installBtn)installBtn.onclick=async()=>{if(isStandalone())return;deferredInstallPrompt=deferredInstallPrompt||window.__dietInstallPrompt;if(deferredInstallPrompt){try{deferredInstallPrompt.prompt();const choice=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;window.__dietInstallPrompt=null;if(choice&&choice.outcome==='accepted'){installBtn.textContent='מתקין…'}updateInstallButton()}catch(err){console.error('Install prompt failed',err);if(installHelp)installHelp.hidden=false}return}if(installHelp)installHelp.hidden=false;};
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});renderAll();updateInstallButton();const initialScreen=(location.hash||'#today').replace('#','');go(validScreen(initialScreen)?initialScreen:'today',false);window.addEventListener('hashchange',()=>{const s=(location.hash||'#today').replace('#','');if(validScreen(s))go(s,false)});

window.addEventListener('resize',()=>{if(document.querySelector('[data-screen="activity"]')?.classList.contains('active'))renderActivities()});window.addEventListener('pageshow',updateInstallButton);
